### ISSUE TITLE
Error when breaking into chrome-extension scripts, or other 'ignored' scripts

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-chrome-debug-core#124]
See https://github.com/Microsoft/vscode-chrome-debug/issues/269#issuecomment-257452020

**Comment by roblourens** [comment]
I should blackbox those...

**Comment by roblourens** [comment]
```
Error processing "scopes": TypeError: Cannot read property 'map' of undefined at ChromeDebugAdapter.scopes (C:\Users\Jacques\.vscode\extensions\msjsdiag.debugger-for-chrome-2.1.2\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeDebugAdapter.js:618:47) at dispatchRequest (C:\Users\Jacques\.vscode\extensions\msjsdiag.debugger-for-chrome-2.1.2\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeDebugSession.js:110:68) at ProtocolServer._handleData (C:\Users\Jacques\.vscode\extensions\msjsdiag.debugger-for-chrome-2.1.2\node_modules\vscode-chrome-debug-core\node_modules\vscode-debugadapter\lib\protocol.js:104:38) at Socket.<anonymous> (C:\Users\Jacques\.vscode\extensions\msjsdiag.debugger-for-chrome-2.1.2\node_modules\vscode-chrome-debug-core\node_modules\vscode-debugadapter\lib\protocol.js:24:60) at emitOne (events.js:96:13) at Socket.emit (events.js:188:7) at readableAddChunk (_stream_readable.js:176:18) at Socket.Readable.push (_stream_readable.js:134:10) at Pipe.onread (net.js:543:20)
```
