### ISSUE TITLE
Nicer error messages when a source map fails to parse

### ISSUE THREAD

**Issue by nojvek** [Microsoft/vscode-chrome-debug-core#187]
```
SourceMaps.getMapForGeneratedPath: exception while processing sourcemap: SyntaxError: Unexpected token w in JSON at position 0
    at new SourceMap (/Users/nojvek/.vscode/extensions/msjsdiag.debugger-for-chrome-2.5.4/node_modules/vscode-chrome-debug-core/out/src/sourceMaps/sourceMap.js:19:25)
    at sourceMapContentsP.then.e (/Users/nojvek/.vscode/extensions/msjsdiag.debugger-for-chrome-2.5.4/node_modules/vscode-chrome-debug-core/out/src/sourceMaps/sourceMapFactory.js:35:24)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

Would be nice to know which of my source maps are broken.

**Comment by roblourens** [comment]
Sure, thanks. You can probably figure it out if you look at the lines above it in the log. Although since they're processed asynchronously, some lines might be interleaved.

**Comment by nojvek** [comment]
Just sent a fix PR

**Comment by roblourens** [comment]
Thanks!
