### ISSUE TITLE
Async stack traces not available on 32bit platforms, node outputs warning

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-chrome-debug-core#321]
Debugging on 32-bit linux, `[INSPECTOR_STACK_TRACES_NOT_AVAILABLE] ...`

**Comment by roblourens** [comment]
I would take a PR

**Comment by rkaliamu** [comment]
Hi,
Any update on this issue. 
I am also facing the same issue.
(node:7172) [INSPECTOR_ASYNC_STACK_TRACES_NOT_AVAILABLE] Warning: Warning: Async stack traces in debugger are not available on 32bit platforms. The feature is disabled.

**Comment by Serha31** [comment]
I'm facing this problem too : [INSPECTOR_ASYNC_STACK_TRACES_NOT_AVAILABLE] Warning: Warning: Async stack traces in debugger are not available on 32bit platforms. The feature is disabled.
warning.js:18

**Comment by UniBreakfast** [comment]
Is there any setting to disable this? Every time I debug node (many many times a day) it shows me four lines of these warnings (two messages that are almost identical). And I really don't need them. I get it. It doesn't like my 32bit system. And I won't get async debugger. Fine. Can it stop "yelling" on me about it?

**Comment by Leonardoleo** [comment]
Hi. Go to VS Code. Then,click Debug => Start Without Debugging. @ use shortcut key,F5. 
Happy coding! :)

**Comment by olgamarinova** [comment]
(node:5792) [INSPECTOR_ASYNC_STACK_TRACES_NOT_AVAILABLE] Warning: Warning: Async stack traces in debugger are not available on 32bit platforms. The feature is disabled.
Windows 8, 64bit

**Comment by olgamarinova** [comment]
(node:5792) [INSPECTOR_ASYNC_STACK_TRACES_NOT_AVAILABLE] Warning: Warning: Async stack traces in debugger are not available on 32bit platforms. The feature is disabled.
Windows 8, 64bit
I downloaded the 64bit version of VS code and Node.js and it still shows this.

**Comment by mevaldovi** [comment]
I am also getting the same error

(node:2620) [INSPECTOR_ASYNC_STACK_TRACES_NOT_AVAILABLE] Warning: Warning: Async stack traces in debugger are not available on 32bit platforms. The feature is disabled.
(Use `node --trace-warnings ...` to show where the warning was created)

i tried running without debugging and restarted my computer, as well as reinstalling the program without extensions. None of these has worked so far.

**Comment by mementoMori-FCDK** [comment]
i am gay

**Comment by abesherman** [comment]
> node --trace-warnings ...
Here is what i got when running  `node --trace-warnings ...`
```
node --trace-warnings ... 
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/home/pi/...'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```
