### ISSUE TITLE
Hermes debugger problems

### ISSUE THREAD

**Issue by RedMickey** [microsoft/vscode-chrome-debug-core#517]
# Hermes debugger problems

Hello, we are the development team of VS Code extension for debugging React Native apps ([vscode-react-native](https://github.com/microsoft/vscode-react-native)). Now we are working on the prototype of React Native Hermes debugger and we've faced several problems of using vscode-chrome-debug-core lib. We think that the problems might be on vscode-chrome-debug-core side, because our implementation extends chromeDebugAdapter without significant structural changes. There are also some issues with React Native Hermes debugging in Chrome itself. Could you please look through the list of problems that we faced with?

Table of problems consists of two columns: first one illustrates the problem when debugging the app with Hermes enabled using prototype of the debugger in the extension, second one - when Chrome is used for debugging the app. Also, there are logs attached for each problem.

Here is a link for sources of the direct debugger: https://github.com/RedMickey/vscode-react-native/tree/react-native-direct-debugger2/src/debugger/direct

## The list of problems

1) The debugger doesn’t show Global, Closure variables. The debugger provides only Local variables (function scope). Google Chrome displays Global variables, but Locals aren't shown.

  |Debugging using VS Code RNT Hermes debugger prototype|Debugging using Chrome|
  |---|---|
  |<img src="https://github.com/RedMickey/vscode-react-native/raw/hermes-debugger-issues/HermesProblemsDescription/images2/ScreenShot2019-08-29at13.05.33.png" alt="drawing"/>|<img src="https://github.com/RedMickey/vscode-react-native/raw/hermes-debugger-issues/HermesProblemsDescription/images2/ScreenShot2019-08-29at13.06.35.png" alt="drawing"/>|

2) The debugger doesn’t show value of numeric variables.

  |Debugging using VS Code RNT Hermes debugger prototype|Debugging using Chrome|
  |---|---|
  |<img src="https://github.com/RedMickey/vscode-react-native/raw/hermes-debugger-issues/HermesProblemsDescription/images2/ScreenShot2019-08-29at15.21.23.png" alt="drawing"/>|<img src="https://github.com/RedMickey/vscode-react-native/raw/hermes-debugger-issues/HermesProblemsDescription/images2/ScreenShot2019-08-29at15.23.59.png" alt="drawing"/>|

3) The debugger shows additional VM_unknown calls in Call Stack.
  <br/>The debugger displays all the calls as well as Google Chrome, but also adds unknown calls.

  |Debugging using VS Code RNT Hermes debugger prototype|Debugging using Chrome|
  |---|---|
  |<img src="https://github.com/RedMickey/vscode-react-native/raw/hermes-debugger-issues/HermesProblemsDescription/images2/ScreenShot2019-08-29at13.10.11.png" alt="drawing"/>|<img src="https://github.com/RedMickey/vscode-react-native/raw/hermes-debugger-issues/HermesProblemsDescription/images2/ScreenShot2019-08-29at13.10.44.png" alt="drawing"/>|

  [Logs](https://github.com/RedMickey/vscode-react-native/blob/hermes-debugger-issues/HermesProblemsDescription/logs/appLogs123.txt) for problems 1, 2, 3.

4) The debugger doesn’t provide complete object data (For example, Date object, Map object - there is only an object name without internal data).
  <br/> If an object contains an array the debugger doesn't display the object's data.
  <br/> Google Chrome displays some objects correctly, but not all (e.g. Map object).
  <br/>The debugger doesn’t provide properties containing in “this” object.

  |Debugging using VS Code RNT Hermes debugger prototype|Debugging using Chrome|
  |---|---|
  |<img src="https://github.com/RedMickey/vscode-react-native/raw/hermes-debugger-issues/HermesProblemsDescription/images2/ScreenShot2019-08-29at13.26.54.png" alt="drawing"/>|<img src="https://github.com/RedMickey/vscode-react-native/raw/hermes-debugger-issues/HermesProblemsDescription/images2/ScreenShot2019-08-29at13.27.40.png" alt="drawing"/>|
  |<img src="https://github.com/RedMickey/vscode-react-native/raw/hermes-debugger-issues/HermesProblemsDescription/images2/ScreenShot2019-08-29at16.11.34.png" alt="drawing"/>|<img src="https://github.com/RedMickey/vscode-react-native/raw/hermes-debugger-issues/HermesProblemsDescription/images2/ScreenShot2019-08-29at15.46.06.png" alt="drawing"/>|

  [Logs](https://github.com/RedMickey/vscode-react-native/blob/hermes-debugger-issues/HermesProblemsDescription/logs/appLogs4-1.txt) for problem 4 - 1 table row.
  <br/>[Logs](https://github.com/RedMickey/vscode-react-native/blob/hermes-debugger-issues/HermesProblemsDescription/logs/appLogs4-2.txt) for problem 4 - 2 table row.

5) The debugger doesn’t show local variables, if there is any array definition in a handler function.
  <br/>The debugger remove local variables data only when it comes an array definition. Google Chrome displays array's data.

  |Debugging using VS Code RNT Hermes debugger prototype|Debugging using Chrome|
  |---|---|
  |Before the array definition: <br/><img src="https://github.com/RedMickey/vscode-react-native/raw/hermes-debugger-issues/HermesProblemsDescription/images2/ScreenShot2019-08-29at15.59.44.png" alt="drawing"/>|<img src="https://github.com/RedMickey/vscode-react-native/raw/hermes-debugger-issues/HermesProblemsDescription/images2/ScreenShot2019-08-29at16.04.51.png" alt="drawing"/>|
  |After the array definition: <br/><img src="https://github.com/RedMickey/vscode-react-native/raw/hermes-debugger-issues/HermesProblemsDescription/images2/ScreenShot2019-08-29at16.00.01.png" alt="drawing"/>||

  [Logs](https://github.com/RedMickey/vscode-react-native/blob/hermes-debugger-issues/HermesProblemsDescription/logs/appLogs5.txt) for problem 5.

**Comment by roblourens** [comment]
Looking at this briefly, for problem 2 I see that this runtime's implementation of the devtools protocol diverges from chrome/node. It isn't giving a `description` property for numeric values, and this library is expecting that: https://github.com/Microsoft/vscode-chrome-debug-core/blob/master/src/chrome/variables.ts#L272

I'm guessing that the others are similar issues. I know very little about React Native, can you tell me how the debugger works here? Is it based on an old version of chrome/a fork, or is it a totally new implementation? If there are lots of little differences then it could be a lot of work to fully support it. Also note that we are working on a large change to this library and it could be more forgiving in some ways. It's in the branch v2 of this repo.

**Comment by RedMickey** [comment]
For debugging React Native Hermes apps we use the direct debugging approach. It means that Hermes engine inside the React Native Android application launches a DevTools server which is waiting for Chrome DevTools Protocol connection. Our extension connects to this server by means of ChromeDebugAdapter.  We took pure ChromeDebugAdapter from lib vscode-chrome-debug-core:^6.7.46 and added specific logic for work with React Native applications in their attach and launch functions, but we call `super.launch` and `super.attach`functions without changes. In the launch function we added special functional for launching Android Hermes apps, but it doesn’t modify base implementations from ChromeDebugAdapter. In the attach function we just added telemetry. @roblourens

**Comment by roblourens** [comment]
Ok, it sounds like this is a new implementation of the chrome debug protocol. It's unfortunate that the protocol is not specced more strictly. We will just have to find these differences, fix them one by one, and add tests. You could test to find out how well the v2 branch is currently working with Hermes. FYI @digeff

**Comment by RedMickey** [comment]
@roblourens @digeff We created the issue about [known React Native Hermes debugging problems](https://github.com/microsoft/vscode-react-native/issues/1099) in our repository and moved the the list of problems there. In this issue we'll collect user's feedback and add new Hermes debugging issues if we face ones.

**Comment by SounD120** [comment]
Hi @roblourens @digeff . A new problem appeared after the VS Code 1.39 update. After setting a breakpoint when debugging Hermes the following message shows up in debug console:
```
Error processing "breakpointLocations": TypeError: Cannot read property 'map' of undefined
    at Breakpoints.<anonymous> (c:\Work\vscode-react-native\node_modules\vscode-chrome-debug-core\out\src\chrome\breakpoints.js:303:68)
    at Generator.next (<anonymous>)
    at fulfilled (c:\Work\vscode-react-native\node_modules\vscode-chrome-debug-core\out\src\chrome\breakpoints.js:7:58)
```
I looked at the code and found out that `possibleBpResponse` could be `undefined` in [such case](https://github.com/microsoft/vscode-chrome-debug-core/blob/31d19232b18071031a9d2489772fb68f1c333e5f/src/chrome/breakpoints.ts#L341-L346).
Attached logs for such case: [chrome-debug-core-session.txt](https://github.com/microsoft/vscode-chrome-debug-core/files/3728274/chrome-debug-core-session.txt)
Could you please take a look?

**Comment by roblourens** [comment]
@SounD120 this isn't related to Hermes, please open a new issue. It sounds like React Native is doing something weird though because `locations` shouldn't be undefined.
