### ISSUE TITLE
Variable hovers sometimes stop showing up

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode-chrome-debug-core#535]
Sometimes during a debugging session, variable hovers will stop showing up. On one of those occasions I noticed the following in the _Debug Output_ pane
 
```
Error processing "variables": TypeError: Cannot destructure property `variables` of 'undefined' or 'null'.
    at ChromeDebugAdapter.<anonymous> (c:\Users\Eric\.vscode-insiders\extensions\msjsdiag.debugger-for-chrome-4.12.1\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeDebugAdapter.js:1167:19)
    at Generator.next (<anonymous>)
    at fulfilled (c:\Users\Eric\.vscode-insiders\extensions\msjsdiag.debugger-for-chrome-4.12.1\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeDebugAdapter.js:7:58)
Error processing "variables": TypeError: Cannot destructure property `variables` of 'undefined' or 'null'.
    at ChromeDebugAdapter.<anonymous> (c:\Users\Eric\.vscode-insiders\extensions\msjsdiag.debugger-for-chrome-4.12.1\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeDebugAdapter.js:1167:19)
    at Generator.next (<anonymous>)
    at fulfilled (c:\Users\Eric\.vscode-insiders\extensions\msjsdiag.debugger-for-chrome-4.12.1\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeDebugAdapter.js:7:58)
```

**Comment by roblourens** [comment]
I am patching the unhandled error but I would appreciate if you can get a log for the next time you see this, because I think it would imply that VS Code is asking for the wrong variables reference at the time, or that the DA has lost it.

**Comment by eamodio** [comment]
Will keep an eye out for it.

**Comment by eamodio** [comment]
@roblourens It happened again (though I know your fix isn't live yet), here is the log:

[vscode-node-debug2.txt](https://github.com/microsoft/vscode-chrome-debug-core/files/3877767/vscode-node-debug2.txt)

**Comment by roblourens** [comment]
Thanks! Yeah FYI @isidorn, the DA paused, and sent scopes to vscode, then resumed, then paused again, and vscode sent a variables request for one of the original scopes, when it should have sent a scopes request.

It could be a race, but vscode did ask for the new stackTrace, so it knew that the DA was paused again at that point.

**Comment by isidorn** [comment]
We update the variables tree with a slight timeout, so that could in theory explain this.

**Comment by roblourens** [comment]
It sounds like something changed though, because I don't remember seeing this before, and now it has been reported a few times.

**Comment by isidorn** [comment]
I did an rewirte from Promises to async/await, that might have caused some timing issue in theory.
Though if there are steps that would be great

**Comment by roblourens** [comment]
It doesn't sound like anyone is able to repro it 100% consistently but there is a log above if it helps.

**Comment by Elias-Graf** [comment]
I'm having the same issue but not consistent. I will see how I can replicate it, but in my case, it seems to occur after (quiet some time) the actual code throws an error.
